version: "3"
services:
  mysql:
    build: ./
    volumes:
      - ./db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: sample-mysql # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=root   #コンテナ内のMySQLを起動する際のパスワードを設定
    ports:
      - "3306:3306"